services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: database-1.ccvw48c4oye3.us-east-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: Tanaka!234#
      DB_NAME: mydb